name: Automerge Dependabot PRs

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        run: |
          if gh pr merge --auto --squash "$PR_URL"; then
            echo "PR merged successfully"
          else
            MERGEABLE=$(gh pr view "$PR_URL" --json mergeable --jq '.mergeable')
            if [ "$MERGEABLE" = "CONFLICTING" ]; then
              gh pr comment "$PR_URL" --body "@dependabot recreate"
            else
              echo "Merge failed for another reason"
            fi
          fi
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
