name: Deploy to Timeweb

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install Cython
        pip install -r requirements.txt

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 94.198.217.12
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          cd /home
          if [ ! -d "ijarago" ]; then
            git clone git@github.com:mehmonov/ijarago.git
          else
            cd /home/ijarago
            git pull origin main
          fi
          cd /home/ijarago
          git fetch origin main
          git reset --hard origin/main
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install wheel
          pip install Cython
          pip install -r requirements.txt
          
          # Setup and restart supervisor
          echo '[program:ijarago]
          directory=/home/ijarago
          command=/home/ijarago/venv/bin/python main.py
          autostart=true
          autorestart=true
          stderr_logfile=/var/log/ijarago.err.log
          stdout_logfile=/var/log/ijarago.out.log
          user=root' > /etc/supervisor/conf.d/ijarago.conf
          supervisorctl reread
          supervisorctl update
          supervisorctl restart ijarago