name: Telegram bot deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 94.198.217.12
        username: root
        password: gcLTffjQ9-BnKd
        script: |
          echo "Deployment boshlandi..."
          
          # Repository papkasiga o'tish
          cd /home/
          echo "Papkaga o'tildi: /home/"
          
          # Eski jarayonni to'xtatish
          if pgrep -f "python3 app.py"; then
            echo "Eski bot jarayoni to'xtatilmoqda..."
            pkill -f "python3 app.py"
          fi
          
          # Repository clone/pull
          if [ ! -d "ijarago" ]; then
            echo "Repository clone qilinmoqda..."
            git clone https://github.com/mehmonov/ijarago.git
            if [ $? -ne 0 ]; then
              echo "Clone qilishda xatolik!"
              exit 1
            fi
          else
            echo "Mavjud repository yangilanmoqda..."
            cd ijarago
            git fetch origin main
            git reset --hard origin/main
            if [ $? -ne 0 ]; then
              echo "Repository yangilashda xatolik!"
              exit 1
            fi
          fi
          
          # Bot papkasiga o'tish
          echo "Bot papkasiga o'tilmoqda..."
          cd /home/ijarago/bot || {
            echo "Bot papkasi topilmadi: /home/ijarago/bot"
            ls -la /home/ijarago/
            exit 1
          }
          
          # Virtual environment yaratish
          echo "Virtual environment yaratilmoqda..."
          python3 -m venv venv || true
          source venv/bin/activate
          
          # Asosiy paketlarni o'rnatish
          echo "Pip yangilanmoqda..."
          pip install --upgrade pip
          
          echo "Paketlar o'rnatilmoqda..."
          pip install aiogram python-dotenv
          
          # Botni ishga tushirish
          echo "Bot ishga tushirilmoqda..."
          nohup python3 app.py > bot.log 2>&1 &
          
          # Bot ishga tushganini tekshirish
          sleep 5
          if pgrep -f "python3 app.py" > /dev/null; then
            echo "Bot muvaffaqiyatli ishga tushirildi!"
          else
            echo "Bot ishga tushirishda xatolik!"
            cat bot.log
            exit 1
          fi
