name: Deploy Telegram Bot

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

env:
  HOST: "94.198.217.12"        # Server IP manzili
  USERNAME: "root"           # Server foydalanuvchi nomi
  PROJECT_NAME: "ijarago" # Loyiha papka nomi
  REPO_URL: "https://github.com/mehmonov/ijarago"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USERNAME }}
        password: "1234"    # Bu yerga to'g'ridan-to'g'ri parolni yozish mumkin
        script: |
          cd /home/
          if [ ! -d "${{ env.PROJECT_NAME }}" ]; then
            git clone ${{ env.REPO_URL }} ${{ env.PROJECT_NAME }}
          else
            cd /home/${{ env.PROJECT_NAME }}
            git pull origin main
          fi
          cd /home/${{ env.PROJECT_NAME }}
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Bot jarayonini qayta ishga tushirish
          if pgrep -f "python3 main.py"; then
            pkill -f "python3 main.py"
          fi
          
          # Botni orqa fonda ishga tushirish
          nohup python3 main.py > bot.log 2>&1 &