name: Deploy Telegram Bot

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: "94.198.217.12"
        username: "root"
        password: "gcLTffjQ9-BnKd"    
        script: |
          cd /home/
          if [ ! -d "ijarago" ]; then
            git clone https://github.com/mehmonov/ijarago
          else
            cd /home/ijarago/bot
            git pull origin main
          fi
          cd /home/ijarago/bot
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          # pip install -r requirements.txt
          
          # Bot jarayonini to'xtatish
          if [ -f "bot.pid" ]; then
            kill -9 `cat bot.pid` || true
            rm bot.pid
          fi
          
          # Eski bot jarayonlarini tozalash
          pkill -f "python3 main.py" || true
          
          # Botni ishga tushirish va PID ni saqlash
          nohup python3 main.py > bot.log 2>&1 & echo $! > bot.pid
          
          echo "Bot muvaffaqiyatli ishga tushirildi!"
          echo "Log faylini tekshirish uchun: tail -f bot.log"