name: Deploy Telegram Bot

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/
          if [ ! -d "${{ secrets.PROJECT_NAME }}" ]; then
            git clone ${{ secrets.REPO_URL }} ${{ secrets.PROJECT_NAME }}
          else
            cd /home/${{ secrets.PROJECT_NAME }}/bot
            git pull origin main
          fi
          cd /home/${{ secrets.PROJECT_NAME }}/bot
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
          if pgrep -f "python3 main.py"; then
            pkill -f "python3 main.py"
          fi
          
          # Botni orqa fonda ishga tushirish
          nohup python3 main.py > bot.log 2>&1 &