name: Telegram bot deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 94.198.217.12
        username: root
        password: gcLTffjQ9-BnKd
        script: |
          echo "Deployment boshlandi..."
          
          # Repository papkasiga o'tish
          cd /home/
          
          # Git config dan foydalanish
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"
          
          # Repository clone/pull
          if [ ! -d "ijarago" ]; then
            echo "Repository clone qilinmoqda..."
            git clone git@github.com:mehmonov/ijarago.git
          else
            echo "Mavjud repository yangilanmoqda..."
            cd ijarago
            git pull origin main
          fi
          
          # Bot papkasini yaratish
          mkdir -p /home/ijarago/bot
          cd /home/ijarago/bot
          
          # Log papkasini yaratish
          mkdir -p /home/ijarago/bot/logs
          
          # Virtual environment yaratish
          python3 -m venv venv || true
          source venv/bin/activate
          
          # Paketlarni o'rnatish
          pip install --upgrade pip
          pip install aiogram python-dotenv
          
          # Supervisor konfiguratsiyasini yaratish
          echo "[program:ijarago_bot]
          directory=/home/ijarago/bot
          command=/home/ijarago/bot/venv/bin/python3 app.py
          autostart=true
          autorestart=true
          stderr_logfile=/home/ijarago/bot/logs/err.log
          stdout_logfile=/home/ijarago/bot/logs/out.log
          environment=HOME='/home/ijarago/bot',USER='root'
          stopasgroup=true
          killasgroup=true" > /etc/supervisor/conf.d/ijarago_bot.conf
          
          # Supervisor ni qayta yuklash
          supervisorctl reread
          supervisorctl update
          supervisorctl restart ijarago_bot
          
          # Bot holatini tekshirish
          sleep 3
          if supervisorctl status ijarago_bot | grep -q RUNNING; then
            echo "Bot muvaffaqiyatli ishga tushirildi!"
            echo "Loglarni tekshirish: tail -f /home/ijarago/bot/logs/out.log"
          else
            echo "Bot ishga tushirishda xatolik!"
            supervisorctl status ijarago_bot
            if [ -f "/home/ijarago/bot/logs/err.log" ]; then
              cat /home/ijarago/bot/logs/err.log
            fi
          fi
