name: Telegram bot deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 94.198.217.12
        username: root
        password: gcLTffjQ9-BnKd
        script: |
          # SSH key sozlash
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          
          # Repository papkasiga o'tish
          cd /home/
          
          # Eski jarayonni to'xtatish
          if pgrep -f "python3 app.py"; then
            pkill -f "python3 app.py"
          fi
          
          # Repository clone/pull
          if [ ! -d "ijarago" ]; then
            # HTTPS orqali clone qilish
            git clone https://github.com/mehmonov/ijarago.git
          else
            cd /home/ijarago
            git fetch origin main
            git reset --hard origin/main
          fi
          
          # Bot papkasiga o'tish
          cd /home/ijarago/bot || {
            echo "Bot papkasi topilmadi!"
            exit 1
          }
          
          # Virtual environment yaratish
          python3 -m venv venv
          source venv/bin/activate
          
          # Asosiy paketlarni o'rnatish
          pip install --upgrade pip
          
          # Agar requirements.txt mavjud bo'lsa
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            # Asosiy kerakli paketlarni o'rnatish
            pip install aiogram python-dotenv
          fi
          
          # Botni ishga tushirish
          echo "Botni ishga tushirish..."
          nohup python3 app.py > bot.log 2>&1 &
          echo "Bot ishga tushirildi!"
